### PR TITLE
Update project to support US Gov cloud for

### PR DESCRIPTION
**Pull request by Sean-Steefel**
Az Management URI changes in reference to issue: #79
@liprec I appreciate the opportunity to contribute - please be critical on reviewing.

### CODE REVIEW

**Comment by liprec** [comment]
@Sean-Steefel: Thanks for the PR and I will look at it tomorrow (for me).

**Comment by annapriyajose** [comment]
@liprec  We would appreciate an update on this? have you got a chance to take a look into the code changes?

**Comment by liprec** [comment]
I will close this PR in favor of retrieving the management url from the Service Connection instead as a provided parameter.
The next version will have support for all Government clouds, including China and Germany if needed.

**Comment by annapriyajose** [comment]
@liprec - Okay Thanks, Can we at least know the estimated time of arrival for next version release then, as our current deployment is awaiting this changes

**Comment by liprec** [comment]
The new version (v2.5) is available and should automatically been updated with Azure DevOps, but sometimes it will take a couple of runs before the latest version will be used.

**Comment by annapriyajose** [comment]
Not able to use the new version yet

**Pull request closed without merging**
